version: 1.0.0a0.dev{build}

environment:
  PYPI_USERNAME: aio-libs-bot
  PYPI_PASSWORD:
    secure: HrwOVde4wZoYHJf9bZ5AsQ==
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install -U setuptools wheel codecov"
  - tools/build.cmd %PYTHON%\\python.exe -m pip install -r requirements/ci.txt

build_script:
  - "tools/build.cmd %PYTHON%\\python.exe setup.py sdist bdist_wheel"

test_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m pytest tests --junitxml=junit-test-results.xml --cov-report term-missing:skip-covered --cov-report xml"

after_test:
  - "tools/build.cmd %PYTHON%\\python.exe -m codecov -f coverage.xml -X gcov"
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit-test-results.xml))

artifacts:
  - path: dist\*

before_deploy:
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install twine"

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          Invoke-Expression "$env:PYTHON\\python.exe -m twine upload dist/* --username $env:PYPI_USERNAME --password $env:PYPI_PASSWORD"
      }

#notifications:
#  - provider: Webhook
#    url: https://ci.appveyor.com/api/github/webhook?id=08c7793w1tp839fl
#    on_build_success: false
#    on_build_failure: True
