version: 1.0.0a0.dev{build}

environment:
  PYPI_USERNAME: aio-libs-bot
  PYPI_PASSWORD:
    secure: HrwOVde4wZoYHJf9bZ5AsQ==
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install -U tox"
  - DEL /S /F ".git"
  - "tools/build.cmd %PYTHON%\\python.exe -m tox --notest"  # Pre-populate a virtualenv with dependencies

build_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m tox -e build-dists"

test_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m tox"

after_test:
  - "tools/build.cmd %PYTHON%\\python.exe -m tox -e codecov"
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit-test-results.xml))

artifacts:
  - path: dist\*

before_deploy:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          Invoke-Expression "tools/build.cmd $env:PYTHON\\python.exe -m tox -e upload-dists --notest"
      }

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          Invoke-Expression "tools/build.cmd $env:PYTHON\\python.exe -m tox -e upload-dists"
      }

#notifications:
#  - provider: Webhook
#    url: https://ci.appveyor.com/api/github/webhook?id=08c7793w1tp839fl
#    on_build_success: false
#    on_build_failure: True
