name: Code quality

on:
  push:
  pull_request:
  schedule:
  # Run every Friday at 18:02 UTC
  # https://crontab.guru/#2_18_*_*_5
  - cron: 2 18 * * 5

jobs:
  linters:
    runs-on: ${{ matrix.os }}
    strategy:
      # max-parallel: 5
      matrix:
        python-version:
        - 3.7
        os:
        - ubuntu-18.04
        env:
        - TOXENV: doc-spelling
          MULTIDICT_NO_EXTENSIONS: X
        - TOXENV: flake8
          MULTIDICT_NO_EXTENSIONS: X
        - TOXENV: mypy
          MULTIDICT_NO_EXTENSIONS: X
        - TOXENV: setup-check
          MULTIDICT_NO_EXTENSIONS: X
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade tox
    - name: 'Initialize tox envs: ${{ matrix.env.TOXENV }}'
      run: |
        python -m tox --parallel auto --notest
      env: ${{ matrix.env }}
    - name: Test with tox
      run: |
        python -m tox --parallel 0
      env: ${{ matrix.env }}
